#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

#PROJECT_NAME := hello-world

PROJECT_NAME := dipcoater_esp2
include $(IDF_PATH)/make/project.mk

